[auth]
password_hash = "5dee43e4e7a08ddcad86c8f88c62591d8c46d7e7181326321b5f9ccf57c80d8b"

[dropbox]
refresh_token = 'jjwplWLMvkAAAAAAAAAAAfH9FFJGfjInqidmC8dRgDBp6-haTG7Ys1bdH5t1f4YO'
client_id = "9f1m6pu1uyzyjhi"
client_secret = "gqg47y05qzt6gyb"
folder_path = "/CVs"